debug = false
source_code = "https://github.com/V4NT-ORG/libremedium"
#cache = "/var/lib/libmedium"

[server]
# The port at which you want authentication to listen to
# takes a number, choose from 1000-10000 if you dont know what you are doing
port = 7000
#IP address. Enter 127.0.0.1 to listen on domain only or Enter 0.0.0.0 to listen on all avaiable addresses.
ip= "127.0.0.1" 
# enter your hostname, eg: example.com
domain = "https://"
allow_registration = true
proxy_has_tls = true
#workers = 2
